
import __ASTRO_IMAGE_IMPORT_ZwRFVf from "../../assets/AP_Sys.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FAccess-Point-System.md";
import __ASTRO_IMAGE_IMPORT_Z1anXvA from "../../assets/EasyMesh.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FEasyMesh-system.md";
import __ASTRO_IMAGE_IMPORT_6LcEl from "../../assets/book-list.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbook-list.md";
import __ASTRO_IMAGE_IMPORT_16Q0hd from "../../assets/poetry.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmy-poetry.md";
import __ASTRO_IMAGE_IMPORT_u2Vfy from "../../assets/samu.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FSamu-trecking.md";
import __ASTRO_IMAGE_IMPORT_iamLp from "../../assets/technology/easymesh/discovery-phase.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FEasyMesh-system.md";
import __ASTRO_IMAGE_IMPORT_Z258yEQ from "../../assets/technology/easymesh/link-metric.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FEasyMesh-system.md";
import __ASTRO_IMAGE_IMPORT_Z1Xsm9m from "../../assets/technology/easymesh/renew-autoconfig.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FEasyMesh-system.md";
import __ASTRO_IMAGE_IMPORT_ZXSdJw from "../../assets/technology/easymesh/topology-management.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FEasyMesh-system.md";
import __ASTRO_IMAGE_IMPORT_Zjr21a from "../../assets/traveling/samu/IMG_1198.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FSamu-trecking.md";
import __ASTRO_IMAGE_IMPORT_iU87y from "../../assets/traveling/samu/IMG_1200.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FSamu-trecking.md";
import __ASTRO_IMAGE_IMPORT_1TEdke from "../../assets/traveling/samu/IMG_1237.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FSamu-trecking.md";
import __ASTRO_IMAGE_IMPORT_vsQkM from "../../assets/traveling/samu/about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FSamu-trecking.md";
import __ASTRO_IMAGE_IMPORT_ZPVH57 from "../../assets/vim_image.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvim.md";
export default new Map([["../../assets/AP_Sys.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FAccess-Point-System.md", __ASTRO_IMAGE_IMPORT_ZwRFVf], ["../../assets/EasyMesh.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FEasyMesh-system.md", __ASTRO_IMAGE_IMPORT_Z1anXvA], ["../../assets/book-list.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbook-list.md", __ASTRO_IMAGE_IMPORT_6LcEl], ["../../assets/poetry.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmy-poetry.md", __ASTRO_IMAGE_IMPORT_16Q0hd], ["../../assets/samu.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FSamu-trecking.md", __ASTRO_IMAGE_IMPORT_u2Vfy], ["../../assets/technology/easymesh/discovery-phase.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FEasyMesh-system.md", __ASTRO_IMAGE_IMPORT_iamLp], ["../../assets/technology/easymesh/link-metric.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FEasyMesh-system.md", __ASTRO_IMAGE_IMPORT_Z258yEQ], ["../../assets/technology/easymesh/renew-autoconfig.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FEasyMesh-system.md", __ASTRO_IMAGE_IMPORT_Z1Xsm9m], ["../../assets/technology/easymesh/topology-management.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FEasyMesh-system.md", __ASTRO_IMAGE_IMPORT_ZXSdJw], ["../../assets/traveling/samu/IMG_1198.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FSamu-trecking.md", __ASTRO_IMAGE_IMPORT_Zjr21a], ["../../assets/traveling/samu/IMG_1200.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FSamu-trecking.md", __ASTRO_IMAGE_IMPORT_iU87y], ["../../assets/traveling/samu/IMG_1237.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FSamu-trecking.md", __ASTRO_IMAGE_IMPORT_1TEdke], ["../../assets/traveling/samu/about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FSamu-trecking.md", __ASTRO_IMAGE_IMPORT_vsQkM], ["../../assets/vim_image.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvim.md", __ASTRO_IMAGE_IMPORT_ZPVH57]]);
		